name: Compile Typst to SVG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Typst
      run: |
        sudo snap install typst

    - name: Compile Typst to SVG
      run: typst compile ksc_poster.typ output.svg

    - name: Upload SVG to Gist
      env:
        GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
      run: |
        gist_id="232e43e34ab57b5e58313db1efcf71fe"
        file_name="ksc_poster.svg"
        svg_content=$(cat output.svg | tr -d '\n' | jq -R)

        curl -X PATCH \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/gists/$gist_id \
          -d $(jq -n --arg desc "Updated svg" --arg file_name "$file_name" --arg content "$svg_content" \
            '{description: $desc, files: {($file_name): {content: $content}}}')
        
