name: Compile Typst to SVG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Typst
      run: |
        sudo snap install typst

    - name: Compile Typst to SVG
      run: typst compile ksc_poster.typ -o output.svg

    - name: Upload SVG to Gist
      env:
        GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
      run: |
        gist_id="232e43e34ab57b5e58313db1efcf71fe"
        file_name="ksc_poster.svg"
        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d @- https://api.github.com/gists/$gist_id <<EOF
        {
          "files": {
            "$file_name": {
              "content": "$(cat output.svg)"
            }
          }
        }
